---
title: "MOR2 data exploration"
author: "G Allington"
date: "3/16/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#load the data
library(foreign)
library(dplyr)
library(ggplot2)
mor2<- read.spss("./data/ALL_EcolHHOrgMerged_byUvuljaa_03_15_17_Simplified.sav" , 
                 to.data.frame=TRUE,
                 use.value.labels=FALSE)
```

## Exploring the database

Some summaries

```{r hist}
hist(mor2$CBRM_type)
sr<- select(mor2, SocialSurveyReferenceNumber,
                  SpeciesRichnessMean500_1000,
                  PerGrassCover_percent_Mean500_1000)
 
# sr x cover x cbrm
x<- mor2 %>% 
  select(CBRM_type, SpeciesRichnessMean500_1000 , PerGrassCover_percent_Mean500_1000)

y<- ggplot(x, aes(x=SpeciesRichnessMean500_1000, 
                  y=PerGrassCover_percent_Mean500_1000, 
                  shape=as.factor(CBRM_type)))+
  geom_point(aes(color=as.factor(CBRM_type)))
y
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(SpeciesRichnessMean500_1000 ~ CBRM_type, data= x)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
